name: "dbt_analytics_demo"
version: "1.0.0"
config-version: 2

profile: "dbt_analytics_demo"

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

models:
  dbt_analytics_demo:
    staging:
      +materialized: ephemeral
    marts:
      +materialized: view
    marts.incremental:
      +materialized: incremental
    marts.table:
      +materialized: table
